"""
client/llm/callback.py - Custom LLM Callback Handlers

This module implements custom callback handlers for LLM streaming output,
providing hooks for monitoring LLM generation lifecycle events.

Key Features:
- Streaming output handling
- LLM start/end event tracking
- Token-by-token generation monitoring

Location: client/llm/callback.py (relative to project root)

Dependencies:
- langchain.callbacks: Base callback implementations
"""

from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from typing import Any, Dict, List


class StreamingCustomCallbackHandler(StreamingStdOutCallbackHandler):
    """
    Custom streaming callback handler for LLM output.

    Extends StreamingStdOutCallbackHandler to add:
    - Explicit start/end markers for LLM generation
    - Raw token streaming with no formatting

    Usage:
        llm = LLM(callbacks=[StreamingCustomCallbackHandler()])
    """

    def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> None:
        """Handle LLM generation start event."""
        print("<LLM Started>")

    def on_llm_end(self, response: Any, **kwargs: Any) -> None:
        """Handle LLM generation completion event."""
        print("<LLM Ended>")

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Handle each new token generated by LLM."""
        print(f"{token}", end="")
